language: ruby
rvm:
- 2.5.5
cache: bundler
addons:
  postgresql: '10'
  apt:
    packages:
    - libarchive-dev
script: bundle exec manageiq-cross_repo
matrix:
  fast_finish: true
branches:
  only:
  - master
env:
  global:
  - REPOS=manageiq-api#985,manageiq#20991,manageiq-providers-autosde#51,manageiq-ui-classic#7587
  matrix:
  - TEST_REPO=manageiq-api
