dist: xenial
language: ruby
rvm:
- 2.5.5
cache:
  bundler: true
addons:
  postgresql: '10'
  apt:
    packages:
    - libarchive-dev
script: bundle exec manageiq-cross_repo
matrix:
  fast_finish: true
env:
  global:
  - REPOS=manageiq-api#932,manageiq#20713
  matrix:
  - TEST_REPO=manageiq-api