language: ruby
rvm:
- 2.5.5
cache: bundler
addons:
  postgresql: '10'
  apt:
    packages:
    - libarchive-dev
script: bundle exec manageiq-cross_repo
matrix:
  fast_finish: true
branches:
  only:
  - master
env:
  global:
  - REPOS=manageiq-providers-autosde#49,manageiq#20858
  matrix:
  - TEST_REPO=manageiq-providers-autosde
